# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/BD_1/BD_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1 || ORIG_REF_NAME==BD_1} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_zynq_ultra_ps_e_0_0/BD_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==BD_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_RV_IP_AXI_Wrapper_0_0/BD_1_RV_IP_AXI_Wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_RV_IP_AXI_Wrapper_0_0 || ORIG_REF_NAME==BD_1_RV_IP_AXI_Wrapper_0_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_xbar_0/BD_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_xbar_0 || ORIG_REF_NAME==BD_1_xbar_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_ps8_0_axi_periph_0/BD_1_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_ps8_0_axi_periph_0 || ORIG_REF_NAME==BD_1_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_rst_ps8_0_99M_0/BD_1_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_rst_ps8_0_99M_0 || ORIG_REF_NAME==BD_1_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_auto_ds_0/BD_1_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_auto_ds_0 || ORIG_REF_NAME==BD_1_auto_ds_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_auto_pc_0/BD_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_auto_pc_0 || ORIG_REF_NAME==BD_1_auto_pc_0} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_auto_ds_1/BD_1_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_auto_ds_1 || ORIG_REF_NAME==BD_1_auto_ds_1} -quiet] -quiet

# IP: bd/BD_1/ip/BD_1_auto_pc_1/BD_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_1_auto_pc_1 || ORIG_REF_NAME==BD_1_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/AISEQ/Desktop/HT/RV/RV.gen/sources_1/bd/BD_1/BD_1_ooc.xdc
