# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/AISEQ/Desktop/HT/RV/RV.srcs/sources_1/bd/BD_1/ip/BD_1_xbar_0/BD_1_xbar_0.xci
# IP: The module: 'BD_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AISEQ/Desktop/HT/RV/RV.gen/sources_1/bd/BD_1/ip/BD_1_xbar_0/BD_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/AISEQ/Desktop/HT/RV/RV.srcs/sources_1/bd/BD_1/ip/BD_1_xbar_0/BD_1_xbar_0.xci
# IP: The module: 'BD_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/AISEQ/Desktop/HT/RV/RV.gen/sources_1/bd/BD_1/ip/BD_1_xbar_0/BD_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BD_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
